<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Home extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('admin_model');
    }

    public function index()
    {
		if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
		{
			redirect('/');
		}

        $data['table_aspirasi']=$this->admin_model->ambil_data();
        $this->load->view('admin/home_admin',$data);    
    } 

    public function result()
    {
        $data['table_solusi']=$this->admin_model->ambil_data_solusi();
        $this->load->view('admin/result',$data); 
    }

    public function form_solusi($id)
    {   
        $asp = $this->admin_model->ambil_data_aspirasi_id($id);
        $solusi1 = $this->admin_model->ambil_data_solusi_aspirasi($asp->aspirasi);
        $data=array(
            'aksi_update' => site_url('admin/Home/aksi_update'),
            'id_solusi' => set_value('id_solusi', $solusi1 ->id_solusi),
            'aspirasi' => set_value('aspirasi', $solusi1->aspirasi),
            'solusi' => set_value('solusi', $solusi1->solusi),
            'button' => 'Kirim' );
        $this->load->view('admin/form_solusi',$data); 
    }

    public function aksi_update()
    {
        $id=$this->input->post('id_solusi');
        $id2=$this->input->post('id_aspirasi');
        $data=array(

            'solusi' => $this->input->post('solusi'),
             'status' => 'Selesai'
            );
 $data1=array(
            'status' => 'Selesai'
            );
        $this->admin_model->update_data($data,$id);
        $this->admin_model->update_status($data1,$id2);
        redirect('admin/Home/result');
    }
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */